{{- if .Values.secrets.enabled -}}
apiVersion: {{ .Values.apiVersions.secret }}
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  logzio-log-shipping-token: {{ required "Logzio shipping token is required!" .Values.secrets.logzioShippingToken }}
  logzio-log-listener: {{ template "logzio.listenerHost" . }}
{{- end }}
